analyzer:
  errors:
    always_specify_types: ignore
    avoid_function_literals_in_foreach_calls: ignore
    avoid_positional_boolean_parameters: ignore
    avoid_redundant_argument_values: ignore
    diagnostic_describe_all_properties: ignore
    flutter_style_todos: ignore
    lines_longer_than_80_chars: ignore
    omit_local_variable_types: ignore
    prefer_asserts_with_message: ignore
    prefer_expression_function_bodies: ignore
    prefer_function_declarations_over_variables: ignore
    prefer_if_elements_to_conditional_expressions: ignore
    sort_child_properties_last: ignore
    missing_required_param: warning
    missing_return: warning
    use_key_in_widget_constructors: ignore
  exclude:
    - lib/domain/model/*.g.dart
    - lib/domain/model/**/*.g.dart
    - lib/datas/network/*.g.dart
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
linter:
  rules:
    # these rules are documented on and in the same order as
    # the Dart Lint rules page to make maintenance easier
    # https://github.com/dart-lang/linter/blob/master/example/all.yaml
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first # we prefer having parameters in the same order as fields https://github.com/flutter/flutter/issues/10219
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_double_and_int_checks
    - avoid_empty_else
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_implementing_value_types
    - avoid_js_rounded_ints
    - avoid_print
    - avoid_renaming_method_parameters
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_shadowing_type_parameters
    - avoid_slow_async_io
    # - avoid_type_to_string # we do this commonly
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - avoid_web_libraries_in_flutter
    - await_only_futures
    - cancel_subscriptions
    # - cast_nullable_to_non_nullable # experimental
    - close_sinks
    - comment_references
    - control_flow_in_finally
    - do_not_use_environment # we do this commonly
    - empty_catches
    - empty_statements
    # - exhaustive_cases warning
    - invariant_booleans
    - iterable_contains_unrelated_type
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_default_cases
    - no_duplicate_case_values
    - no_logic_in_create_state
    - no_runtimeType_toString
    # - null_check_on_nullable_type_parameter # warning
    - null_closures
    - omit_local_variable_types
    - only_throw_errors
    - overridden_fields
    - package_names
    - package_prefixed_library_names
    - prefer_asserts_in_initializer_lists
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_if_null_operators
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_is_not_operator
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - provide_deprecation_message
    - recursive_getters
    - sized_box_for_whitespace # not yet tested
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    # - tighten_type_of_initializing_formals # warning
    - unawaited_futures # too many false positives
    - unnecessary_await_in_return # not yet tested
#    - unnecessary_final
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks # not yet tested
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations # warning
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - implementation_imports
    - avoid_relative_lib_imports
    - prefer_relative_imports
    - avoid_init_to_null
    - prefer_adjacent_string_concatenation
    - unrelated_type_equality_checks
    - unsafe_html
    - unnecessary_brace_in_string_interps
    - use_rethrow_when_possible
    - prefer_collection_literals
    - avoid_function_literals_in_foreach_calls
    - use_full_hex_values_for_flutter_colors
    - prefer_interpolation_to_compose_strings
    - use_function_type_syntax_for_parameters # not yet tested
    - use_is_even_rather_than_modulo # warning
    # - use_late_for_private_fields_and_variables # warning
    - use_raw_strings
    - valid_regexps
    - void_checks
